#!/bin/bash

img=img.qcow2
d=/var/lib/openqa/factory/iso/
if [ "$arch" = 'aarch64' ]; then
    iso=$d/openSUSE-Factory-NET-aarch64-CURRENT-Media.iso
else
    iso=$d/SLE-12-SP1-Server-DVD-x86_64-Build2774-Media1.iso
#    iso=$d/openSUSE-Leap-42.1-DVD-x86_64-Build0207-Media.iso
fi
iso1=$d/SLE-12-SP1-SDK-DVD-x86_64-Build0954-Media1.iso
iso2=$d/SLE-12-SP1-HA-DVD-x86_64-Build0269-Media1.iso

biosdir=/usr/share/qemu/
if [ -n "$uefi" ]; then
    bios=(
        -drive if=pflash,format=raw,readonly,file=$biosdir/ovmf-x86_64-ms-code.bin
        -drive if=pflash,format=raw,file=$biosdir/ovmf-x86_64-ms-vars.bin,snapshot=on
        -debugcon file:debug.log -global isa-debugcon.iobase=0x402
        )
    #bios=(-bios $biosdir/ovmf-x86_64-ms.bin)
fi

qemu()
{
    [ -e "$img" ] || qemu-img create -f qcow2 "$img" 10G
    if [ "$arch" = 'aarch64' ]; then
        iso=$d/openSUSE-Factory-NET-aarch64-CURRENT-Media.iso
        cmd=(qemu-system-aarch64
            -machine virt
            -cpu cortex-a57
            -bios $biosdir/qemu-uefi-aarch64.bin
#        -drive if=pflash,format=raw,readonly,file=$biosdir/qemu-uefi-aarch64.bin
#        -drive if=pflash,format=raw,file=$biosdir/ovmf-x86_64-ms-vars.bin,snapshot=on
            -device VGA -vga std
            -device usb-ehci
            -device usb-kbd
            )
    else
        cmd=(qemu-system-x86_64
            -enable-kvm
            "${bios[@]}"
            )
    fi
    set -x
    exec "${cmd[@]}" \
	-m 1024 \
	-monitor stdio \
	"$@"
}

# vim: sw=4 et
