#!/bin/bash

. common

qemu \
    -device usb-ehci -device usb-tablet \
    -device usb-kbd \
    -drive file="$img",cache=unsafe,if=none,id=hd1 \
    -device virtio-blk,drive=hd1 \
    -drive file=$iso,if=none,id=cd0,format=raw,media=cdrom,readonly=on \
    -device virtio-blk,drive=cd0 \
    -drive file=$iso1,if=none,id=cd1,format=raw,media=cdrom,readonly=on \
    -device virtio-blk,drive=cd1 \
    -drive file=$iso2,if=none,id=cd2,format=raw,media=cdrom,readonly=on \
    -device virtio-blk,drive=cd2 \
    "$@"
